language: node_js
node_js:
  - "6"

env:
  global:
    - secure: Pho0BQ57Qkt8CVk5WZPre4OOdMmdYPdkhZ5Iw0L8ljMTgFlxmpRdWH8KuegOOReo55QS9PR59RX0tucfyZf3ZWSvBt7Ppu+5nzNqeVuHY9B+V9TcGKJ8/mRwcWeMtLOCqiEkE9FvzzDWT8GAbIvTdJPm3a9BaQOu0VjgUmk6QSc=
    - secure: g5bsf4gK72UT92ItMx7Ip4YtrxpCS6znf4T3JmHVysvkbqMyLhm3fVLMBGH9G9IILbNXMiKoPy8L++GNN4XFXdKqQs8HaSe6WhQBHAGaqq8bGRtVYxOd85RdcIwZXbym2ENfGZSSJP+6DzlEIoJzTEiMSmiPY0LO0xlnhL/fOwk=
    - secure: TNWPAW/cme6b/U99Ka1Y1BKBmgK+1gHceNFgFB1SLlaZ9SU1phVfSW9jxETRAN7zdJuvhsr6orYRBxZ0rxmtOsu6/YgUVSY4kRS9Pn82tOzjV3+qP2sydAw8DaujSG9QnuIjfqQLKPhyJ7eAZnFaccLU/c8iEcpYdQzQ8fhAa+c=

before_install:
  - sudo apt-get install ncftp

before_script:
  - npm install

script: ./node_modules/.bin/harp compile

after_success:
  - "ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD $FTP_HOST / www/*"
