language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: Pho0BQ57Qkt8CVk5WZPre4OOdMmdYPdkhZ5Iw0L8ljMTgFlxmpRdWH8KuegOOReo55QS9PR59RX0tucfyZf3ZWSvBt7Ppu+5nzNqeVuHY9B+V9TcGKJ8/mRwcWeMtLOCqiEkE9FvzzDWT8GAbIvTdJPm3a9BaQOu0VjgUmk6QSc=
    - secure: aM9jxNsSK7Z//Yy6J14RIMa7+Vp3LWG5VpCsNmDYB67KR9vlf9eCG+gXau8+TYP54vcl5lvxS6ojsFoNl+z7CaEDOMZCqIKojCkWCWa2Ufcz5bZC8pVjRUOTUMQ7FoJwSA3SYMoLIlTlr1Wf8TzwWHK7sXvfzipJeDRyREZc9V8=
    - secure: TNWPAW/cme6b/U99Ka1Y1BKBmgK+1gHceNFgFB1SLlaZ9SU1phVfSW9jxETRAN7zdJuvhsr6orYRBxZ0rxmtOsu6/YgUVSY4kRS9Pn82tOzjV3+qP2sydAw8DaujSG9QnuIjfqQLKPhyJ7eAZnFaccLU/c8iEcpYdQzQ8fhAa+c=

before_install:
  - sudo apt-get install ncftp
  - npm install -g typescript@1.5.0-alpha

before_script:
  - npm install
  - ./node_modules/.bin/bower install
  - cd public/a/pages && tsc && cd ../../../

script: ./node_modules/.bin/harp compile

after_success:
  - "ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD $FTP_HOST / www/*"
